# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: meterservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='meterservice.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\020MeterReader.gRPC',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12meterservice.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"V\n\rReadingPacket\x12!\n\x08Readings\x18\x01 \x03(\x0b\x32\x0f.ReadingMessage\x12\"\n\nSuccessful\x18\x02 \x01(\x0e\x32\x0e.ReadingStatus\"\x8c\x01\n\x0eReadingMessage\x12\x12\n\nCustomerId\x18\x01 \x01(\x05\x12\x14\n\x0cReadingValue\x18\x02 \x01(\x05\x12\r\n\x05Notes\x18\x03 \x01(\t\x12/\n\x0bReadingTime\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x04\x10\x05R\nSuccessful\">\n\rStatusMessage\x12\x1e\n\x06Status\x18\x01 \x01(\x0e\x32\x0e.ReadingStatus\x12\r\n\x05Notes\x18\x02 \x01(\t*6\n\rReadingStatus\x12\x0b\n\x07Unknown\x10\x00\x12\x0b\n\x07Success\x10\x01\x12\x0b\n\x07\x46\x61ilure\x10\x02\x32\x42\n\x12MeterReaderService\x12,\n\nAddReading\x12\x0e.ReadingPacket\x1a\x0e.StatusMessageB\x13\xaa\x02\x10MeterReader.gRPCb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_READINGSTATUS = _descriptor.EnumDescriptor(
  name='ReadingStatus',
  full_name='ReadingStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Success', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failure', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=350,
  serialized_end=404,
)
_sym_db.RegisterEnumDescriptor(_READINGSTATUS)

ReadingStatus = enum_type_wrapper.EnumTypeWrapper(_READINGSTATUS)
Unknown = 0
Success = 1
Failure = 2



_READINGPACKET = _descriptor.Descriptor(
  name='ReadingPacket',
  full_name='ReadingPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Readings', full_name='ReadingPacket.Readings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Successful', full_name='ReadingPacket.Successful', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=141,
)


_READINGMESSAGE = _descriptor.Descriptor(
  name='ReadingMessage',
  full_name='ReadingMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CustomerId', full_name='ReadingMessage.CustomerId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadingValue', full_name='ReadingMessage.ReadingValue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Notes', full_name='ReadingMessage.Notes', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ReadingTime', full_name='ReadingMessage.ReadingTime', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=284,
)


_STATUSMESSAGE = _descriptor.Descriptor(
  name='StatusMessage',
  full_name='StatusMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Status', full_name='StatusMessage.Status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Notes', full_name='StatusMessage.Notes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=348,
)

_READINGPACKET.fields_by_name['Readings'].message_type = _READINGMESSAGE
_READINGPACKET.fields_by_name['Successful'].enum_type = _READINGSTATUS
_READINGMESSAGE.fields_by_name['ReadingTime'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATUSMESSAGE.fields_by_name['Status'].enum_type = _READINGSTATUS
DESCRIPTOR.message_types_by_name['ReadingPacket'] = _READINGPACKET
DESCRIPTOR.message_types_by_name['ReadingMessage'] = _READINGMESSAGE
DESCRIPTOR.message_types_by_name['StatusMessage'] = _STATUSMESSAGE
DESCRIPTOR.enum_types_by_name['ReadingStatus'] = _READINGSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadingPacket = _reflection.GeneratedProtocolMessageType('ReadingPacket', (_message.Message,), {
  'DESCRIPTOR' : _READINGPACKET,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:ReadingPacket)
  })
_sym_db.RegisterMessage(ReadingPacket)

ReadingMessage = _reflection.GeneratedProtocolMessageType('ReadingMessage', (_message.Message,), {
  'DESCRIPTOR' : _READINGMESSAGE,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:ReadingMessage)
  })
_sym_db.RegisterMessage(ReadingMessage)

StatusMessage = _reflection.GeneratedProtocolMessageType('StatusMessage', (_message.Message,), {
  'DESCRIPTOR' : _STATUSMESSAGE,
  '__module__' : 'meterservice_pb2'
  # @@protoc_insertion_point(class_scope:StatusMessage)
  })
_sym_db.RegisterMessage(StatusMessage)


DESCRIPTOR._options = None

_METERREADERSERVICE = _descriptor.ServiceDescriptor(
  name='MeterReaderService',
  full_name='MeterReaderService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=406,
  serialized_end=472,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddReading',
    full_name='MeterReaderService.AddReading',
    index=0,
    containing_service=None,
    input_type=_READINGPACKET,
    output_type=_STATUSMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METERREADERSERVICE)

DESCRIPTOR.services_by_name['MeterReaderService'] = _METERREADERSERVICE

# @@protoc_insertion_point(module_scope)
